################################################################################
# Base Configuration
################################################################################
version: 2

updates:
  ################################################################################
  # NPM Dependencies
  ################################################################################
  - package-ecosystem: npm
    directory: "/"
    labels:
      - "automerge"
    schedule:
      interval: weekly
    open-pull-requests-limit: 25

    groups:
      ############################################################################
      # Minor and Patch Updates
      ############################################################################
      effect-minor-patch:
        patterns:
          - "@effect/*"
          - "effect"
        update-types: ["minor", "patch"]

      drizzle-minor-patch:
        patterns:
          - "drizzle-orm"
          - "drizzle-kit"
        update-types: ["minor", "patch"]

      other-minor-patch:
        patterns: ["*"]
        exclude-patterns:
          - "@effect/*"
          - "effect"
          - "drizzle-orm"
          - "drizzle-kit"
        update-types: ["minor", "patch"]

      ############################################################################
      # Major Updates
      ############################################################################
      effect-major:
        patterns:
          - "@effect/*"
          - "effect"
        update-types: ["major"]

      drizzle-major:
        patterns:
          - "drizzle-orm"
          - "drizzle-kit"
        update-types: ["major"]

      typescript-major:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "@total-typescript/*"
        update-types: ["major"]

      vitest-major:
        patterns:
          - "vitest"
          - "@vitest/*"
        update-types: ["major"]

  ################################################################################
  # GitHub Actions
  ################################################################################
  - package-ecosystem: github-actions
    directory: "/"
    labels:
      - "automerge"
    schedule:
      interval: weekly
